-- Smart HAS - Sistema de Automação Residencial
-- Criação das tabelas principais

-- Tabela de Usuários
CREATE TABLE USUARIO (
    ID NUMBER PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    SENHA VARCHAR2(255) NOT NULL,
    NOME VARCHAR2(100),
    DATA_CADASTRO DATE DEFAULT SYSDATE
);

-- Tabela de Sensores
CREATE TABLE SENSOR (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    TIPO VARCHAR2(20) NOT NULL, -- TEMPERATURA, UMIDADE, MOVIMENTO, LUZ
    LOCALIZACAO VARCHAR2(50),
    STATUS VARCHAR2(10) DEFAULT 'ATIVO',
    DATA_INSTALACAO DATE DEFAULT SYSDATE
);

-- Tabela de Leituras dos Sensores
CREATE TABLE LEITURA_SENSOR (
    ID NUMBER PRIMARY KEY,
    SENSOR_ID NUMBER REFERENCES SENSOR(ID),
    VALOR NUMBER(10,2) NOT NULL,
    UNIDADE VARCHAR2(10),
    DATA_LEITURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Alertas
CREATE TABLE ALERTA (
    ID NUMBER PRIMARY KEY,
    SENSOR_ID NUMBER REFERENCES SENSOR(ID),
    USUARIO_ID NUMBER REFERENCES USUARIO(ID),
    TIPO VARCHAR2(20) NOT NULL,
    MENSAGEM VARCHAR2(500),
    CRITICIDADE VARCHAR2(10) DEFAULT 'MEDIA', -- BAIXA, MEDIA, ALTA
    DATA_ALERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(15) DEFAULT 'PENDENTE' -- PENDENTE, LIDO, RESOLVIDO
);

-- Tabela de Consumo Energético
CREATE TABLE CONSUMO_ENERGIA (
    ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER REFERENCES USUARIO(ID),
    DISPOSITIVO VARCHAR2(50),
    CONSUMO_KWH NUMBER(10,3),
    CUSTO NUMBER(10,2),
    DATA_CONSUMO DATE,
    MES_ANO VARCHAR2(7) -- formato MM/YYYY
);

-- Sequences
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SENSOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LEITURA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONSUMO START WITH 1 INCREMENT BY 1;

-- Triggers para auto-incremento
CREATE OR REPLACE TRIGGER TRG_USUARIO_ID
    BEFORE INSERT ON USUARIO
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_USUARIO.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_SENSOR_ID
    BEFORE INSERT ON SENSOR
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_SENSOR.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_LEITURA_ID
    BEFORE INSERT ON LEITURA_SENSOR
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_LEITURA.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_ALERTA_ID
    BEFORE INSERT ON ALERTA
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_ALERTA.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_CONSUMO_ID
    BEFORE INSERT ON CONSUMO_ENERGIA
    FOR EACH ROW
BEGIN
    :NEW.ID := SEQ_CONSUMO.NEXTVAL;
END;