-- Smart HAS - H2 Database (simulando Oracle)

-- Tabela de Usuários
CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(100),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Sensores
CREATE TABLE SENSOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    LOCALIZACAO VARCHAR(50),
    STATUS VARCHAR(10) DEFAULT 'ATIVO',
    DATA_INSTALACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Leituras dos Sensores
CREATE TABLE LEITURA_SENSOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SENSOR_ID BIGINT REFERENCES SENSOR(ID),
    VALOR DECIMAL(10,2) NOT NULL,
    UNIDADE VARCHAR(10),
    DATA_LEITURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Alertas
CREATE TABLE ALERTA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SENSOR_ID BIGINT REFERENCES SENSOR(ID),
    USUARIO_ID BIGINT REFERENCES USUARIO(ID),
    TIPO VARCHAR(20) NOT NULL,
    MENSAGEM VARCHAR(500),
    CRITICIDADE VARCHAR(10) DEFAULT 'MEDIA',
    DATA_ALERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(15) DEFAULT 'PENDENTE'
);

-- Tabela de Consumo Energético
CREATE TABLE CONSUMO_ENERGIA (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID BIGINT REFERENCES USUARIO(ID),
    DISPOSITIVO VARCHAR(50),
    CONSUMO_KWH DECIMAL(10,3),
    CUSTO DECIMAL(10,2),
    DATA_CONSUMO DATE,
    MES_ANO VARCHAR(7)
);