-- Inserção de dados simulados para Smart HAS

-- Usuários
INSERT INTO USUARIO (EMAIL, SENHA, NOME) VALUES ('admin@smarthas.com', 'admin123', 'Administrador');
INSERT INTO USUARIO (EMAIL, SENHA, NOME) VALUES ('joao@email.com', 'senha123', 'João Silva');
INSERT INTO USUARIO (EMAIL, SENHA, NOME) VALUES ('maria@email.com', 'senha456', 'Maria Santos');

-- Sensores
INSERT INTO SENSOR (NOME, TIPO, LOCALIZACAO) VALUES ('Temp Sala', 'TEMPERATURA', 'Sala de Estar');
INSERT INTO SENSOR (NOME, TIPO, LOCALIZACAO) VALUES ('Umid Quarto', 'UMIDADE', 'Quarto Principal');
INSERT INTO SENSOR (NOME, TIPO, LOCALIZACAO) VALUES ('Mov Entrada', 'MOVIMENTO', 'Entrada Principal');
INSERT INTO SENSOR (NOME, TIPO, LOCALIZACAO) VALUES ('Luz Cozinha', 'LUZ', 'Cozinha');
INSERT INTO SENSOR (NOME, TIPO, LOCALIZACAO) VALUES ('Temp Quarto', 'TEMPERATURA', 'Quarto Principal');

-- Leituras dos Sensores (últimos 7 dias)
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (1, 23.5, '°C');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (1, 24.2, '°C');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (1, 22.8, '°C');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (2, 65.0, '%');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (2, 68.5, '%');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (3, 1, 'bool');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (3, 0, 'bool');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (4, 450, 'lux');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (5, 19.2, '°C');
INSERT INTO LEITURA_SENSOR (SENSOR_ID, VALOR, UNIDADE) VALUES (5, 20.1, '°C');

-- Consumo Energético
INSERT INTO CONSUMO_ENERGIA (USUARIO_ID, DISPOSITIVO, CONSUMO_KWH, CUSTO, DATA_CONSUMO, MES_ANO) 
VALUES (2, 'Ar Condicionado', 45.5, 32.85, SYSDATE-30, TO_CHAR(SYSDATE-30, 'MM/YYYY'));

INSERT INTO CONSUMO_ENERGIA (USUARIO_ID, DISPOSITIVO, CONSUMO_KWH, CUSTO, DATA_CONSUMO, MES_ANO) 
VALUES (2, 'Geladeira', 28.2, 20.34, SYSDATE-30, TO_CHAR(SYSDATE-30, 'MM/YYYY'));

INSERT INTO CONSUMO_ENERGIA (USUARIO_ID, DISPOSITIVO, CONSUMO_KWH, CUSTO, DATA_CONSUMO, MES_ANO) 
VALUES (3, 'Chuveiro Elétrico', 67.8, 48.92, SYSDATE-30, TO_CHAR(SYSDATE-30, 'MM/YYYY'));

COMMIT;