// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_qZT4ORvCMcBMC-HzNgU7JQrYizDmZNg',
    appId: '1:579243881828:web:425096d802a98eddcd3671',
    messagingSenderId: '579243881828',
    projectId: 'tea-routine',
    authDomain: 'tea-routine.firebaseapp.com',
    storageBucket: 'tea-routine.firebasestorage.app',
    measurementId: 'G-SMD8N37ZNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8AA4rKsGY08NBm1vJCk7bvrm12F0I0Vg',
    appId: '1:579243881828:android:9283d13fe9f0770ccd3671',
    messagingSenderId: '579243881828',
    projectId: 'tea-routine',
    storageBucket: 'tea-routine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhUoi_moV3cKWiHNW4h9kG5e1oZ62V4tI',
    appId: '1:579243881828:ios:b2390e7764a0d634cd3671',
    messagingSenderId: '579243881828',
    projectId: 'tea-routine',
    storageBucket: 'tea-routine.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}